apiVersion: apps/v1
kind: Deployment
metadata:
  name: jekylldeployment
spec:
  template:
    spec:
      containers:
      - name: blog-serve
        resources:
          limits:
            memory: 512Mi