apiVersion: apps/v1
kind: Deployment
metadata:
  name: jekylldeployment
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jekyllpreview
  template:
    metadata:
#      annotations:
#        prometheus.io/scrape: 'true'
#        prometheus.io/path: /metrics
#        prometheus.io/port: '8080'
    spec:
      serviceAccountName: previewd-sa 
      initContainers:
      - name: deploy-init-jek
        image: registry.hub.docker.com/clarkezone/previewd:latest
          #image: registry.dev.clarkezone.dev/previewd:latest
        imagePullPolicy: Always
        command: ["./JekyllBlogPreview"]
        args: ["-initialclone", "true"]
        env:
          - name: JEKPREV_REPO
#            value: https://gitea.homelab.clarkezone.dev/clarkezone/clarkezoneblog.git
            value: https://github.com/clarkezone/clarkezone.github.io.git
          - name: JEKPREV_LOCALDIR
            value: /jekyll
          - name: JEKPREV_initialBranchName
            value: master
#            value: flatter
        volumeMounts:
          - mountPath: /jekyll
            name: blogsource
      containers:
      - name: blog-serve
        image: nginx:1.20-alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          #subPath: "site/html"
          name: blogrender
          readOnly: true
      - name: previewd-server
        image: registry.hub.docker.com/clarkezone/previewd:latest
          #image: registry.dev.clarkezone.dev/previewd:latest
        #command: ["./JekyllBlogPreview"]
        #args: ["-initialbuild", "true", "-clusterinternal", "true"]

        command: ['sh', '-c', "--"]
        args: ["./JekyllBlogPreview -initialbuild=true -incluster=true"]

        ports:
        - containerPort: 80
      volumes:
        - name: blogsource
          persistentVolumeClaim:
            claimName: blogsource-pvc
        - name: blogrender
          persistentVolumeClaim:
            claimName: blogrender-pvc
