apiVersion: batch/v1
kind: Job
metadata:
  name: jekyllrender-job
spec:
  template:
    spec:
      containers:
      - name: jekyll-render-container
        image: registry.dev.clarkezone.dev/jekyllbuilder:arm
        command: ['sh', '-c', "--"]
        args: ["cd source;bundle install;bundle exec jekyll build -d /site JEKYLL_ENV=production"]
        #args: ["cd source;bundle install;bundle exec jekyll build -d /site JEKYLL_ENV=production;while true; do sleep 30000; done"]
        volumeMounts:
          - mountPath: /src
            name: blogsource
            readOnly: true
          - mountPath: /site
            name: blogrender
      restartPolicy: Never 
      volumes:
        - name: blogsource
          persistentVolumeClaim:
            claimName: blogsource-pvc
        - name: blogrender
          persistentVolumeClaim:
            claimName: blogrender-pvc
  backoffLimit: 1
