apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jekyllpreview
commonLabels:
  app: jekyllpreview
resources:
- namespace.yaml
- deployment.yaml
- persistentvolumeclaim.yaml
- service.yaml
- ingress.yaml
- rbac.yaml
