---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: previewd-sa
  labels:
    app: jekyllpreview

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: previewd-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: previewd-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: previewd-role
subjects:
- kind: ServiceAccount
  namespace: jekyllpreview
  name: previewd-sa
