apiVersion: v1
kind: Service
metadata:
  labels:
    app: blogpreview-nginx-serve
  name: blogpreview-nginx-serve-service
spec:
  selector:
    app: nginx-serve
  ports:
    - name: listener
      port: 80
